development:
  adapter: postgresql
  encoding: unicode
  database: lolametro-dev
  pool: 5
  username: brandoncox 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: lolametro-test
  pool: 5
  username: brandoncox 
  password:
